on:
  workflow_dispatch:
  pull_request:
    branches: 
      - "main"

jobs:
  init-runner:
    outputs:
      instance-id: ${{ steps.create-runner.outputs.ID }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup Python libs
        run: |
          python -m pip install --upgrade pip boto3
      - name: create-runner
        id: create-runner
        run: |
          output=$(python3 testops/provisioning/create_script.py ${{ secrets.AWS_ACCESS_KEY_ID }} ${{ secrets.AWS_SECRET_ACCESS_KEY }} ${{ secrets.GH_TOKEN }})
          echo "ID=$output" >> $GITHUB_OUTPUT
          echo $output

  build:
    runs-on: self-hosted
    needs: init-runner
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses:  actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2
      - name: compile
        run: mvn compile
  test:
    runs-on: self-hosted
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses:  actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Install docker
        run: |
          sudo amazon-linux-extras install docker
          sudo service docker start
          sudo usermod -a -G docker ec2-user
          sudo curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version
      - name: start selenoid
        run: ./testops/run-selenoid.sh
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2
      - name: test
        run: mvn clean test
  destroy-runner:
    runs-on: ubuntu-latest
    needs:
      - test
      - init-runner
    if: ${{ always() && !cancelled() }}
    steps:
      - uses: actions/checkout@v4
      - name: setup Python libs
        run: |
          python -m pip install --upgrade pip boto3
      - name: Destroy runner
        run: python3 testops/provisioning/delete_script.py ${{ secrets.AWS_ACCESS_KEY_ID }} ${{ secrets.AWS_SECRET_ACCESS_KEY }} ${{ needs.init-runner.outputs.instance-id }}

