on:
  workflow_dispatch:
  pull_request:
    branches: 
      - "main"

jobs:
  init-runner:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./testops/terraform

      - name: Apply Terraform configuration
        run: terraform apply -auto-approve
        working-directory: ./testops/terraform
        env:
          TF_VAR_gh_token: ${{ secrets.GH_TOKEN }}
  build:
    needs: init-runner
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses:  actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: compile
        run: mvn compile
  test:
    runs-on: self-hosted
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses:  actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: start selenoid
        run: ./testops/run-selenoid.sh
      - name: test
        run: mvn clean test
  destroy-runner:
    runs-on: ubuntu-latest
    needs: test
    if: always()
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: "eu-north-1"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./testops/terraform

      - name: Destroy Terraform configuration
        run: terraform destroy -auto-approve
        working-directory: ./testops/terraform
        env:
          TF_VAR_gh_token: ${{ secrets.GH_TOKEN }}
