on:
  workflow_dispatch:
  pull_request:
    branches: 
      - "main"

jobs:
  init-runner:
    outputs:
      init-success: ${{ job.status }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python libs
        run: |
          python -m pip install --upgrade pip boto3
      - name: Create runner
        run: |
          output=$(python3 testops/provisioning/create_script.py ${{ secrets.AWS_ACCESS_KEY_ID }} ${{ secrets.AWS_SECRET_ACCESS_KEY }} ${{ secrets.GH_TOKEN }})
          echo "::set-output name=output_id::$output"  # Set as step output

  build:
    runs-on: self-hosted
    needs: init-runner
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Set up Apache Maven
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - name: Compile
        run: mvn compile

  test:
    runs-on: self-hosted
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Set up Apache Maven
        uses: actions/setup-maven@v3
        with:
          maven-version: '3.8.4'
          cache: 'maven'
      - name: Start Selenoid
        run: ./testops/run-selenoid.sh
      - name: Test
        run: mvn clean test

  destroy-runner:
    runs-on: ubuntu-latest
    needs:
      - test
      - init-runner
    if: ${{ needs.init-runner.outputs.init-success == 'true' }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python libs
        run: |
          ./testops/provisioning/modules.sh
          source ./bin/activate
      - name: Destroy runner
        run: python3 testops/provisioning/delete_script.py ${{ secrets.AWS_ACCESS_KEY_ID }} ${{ secrets.AWS_SECRET_ACCESS_KEY }} "${{ steps.init-runner.outputs.output_id }}"
